"""
SmartFeed AI - Step 6 Unit Tests
Validates QR code generation, QR image decoding, and Digital Feed Passport assembly.
"""

import os
import sys
import unittest
import tempfile
import uuid
from pathlib import Path

# Add project root to sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from db.database import create_test, delete_test, initialize_database
from utils.qr_utils import generate_feed_passport_qr, decode_qr_image, get_digital_feed_passport


class TestQRPassport(unittest.TestCase):
    def setUp(self):
        # Generate unique test ID to avoid collisions
        unique_suffix = uuid.uuid4().hex[:6].upper()
        self.test_batch_id = f"SFA-2026-{unique_suffix}"
        self.temp_qr_fd, self.temp_qr_path = tempfile.mkstemp(suffix=".png")
        os.close(self.temp_qr_fd)

        initialize_database()

        # Insert test batch record
        self.sample_record = {
            "batch_id": self.test_batch_id,
            "sample_type": "Compound Cattle Feed",
            "image_path": "uploads/test_passport.jpg",
            "visual_prediction": "Good Quality",
            "confidence": 0.95,
            "quality_score": 86.0,
            "mould_risk": "Low",
            "foreign_particle_risk": "Low",
            "adulteration_risk": "Low",
            "nutrition_status": "Balanced",
            "crude_protein": 20.0,
            "moisture": 10.0,
            "fiber": 11.5,
            "storage_condition": "Well-Ventilated Dry Area",
            "overall_risk": "Low",
            "primary_concern": "None",
            "advisory": "Feed is safe for livestock.",
            "language": "en",
            "timestamp": "2026-09-05T12:00:00"
        }
        create_test(self.sample_record)

    def tearDown(self):
        delete_test(self.test_batch_id)
        if os.path.exists(self.temp_qr_path):
            try:
                os.remove(self.temp_qr_path)
            except Exception:
                pass

    def test_generate_and_decode_qr(self):
        """Generate QR code and decode it back to match the original Batch ID."""
        saved_path = generate_feed_passport_qr(self.test_batch_id, output_path=self.temp_qr_path)
        self.assertTrue(os.path.exists(saved_path))
        self.assertGreater(os.path.getsize(saved_path), 0)

        # Decode using OpenCV / pyzbar
        decoded_id = decode_qr_image(saved_path)
        self.assertEqual(decoded_id, self.test_batch_id)

    def test_get_digital_feed_passport(self):
        """Verify complete digital passport data retrieval from database."""
        passport = get_digital_feed_passport(self.test_batch_id)
        self.assertIsNotNone(passport)
        self.assertEqual(passport["batch_id"], self.test_batch_id)
        self.assertEqual(passport["quality_score"], 86.0)
        self.assertIn("Safe", passport["quality_badge"])
        self.assertEqual(passport["nutrients"]["crude_protein"], 20.0)
        self.assertIn("Digital Feed Passport is generated by SmartFeed AI", passport["disclaimer"])

    def test_nonexistent_batch_passport(self):
        """Non-existent batch returns None."""
        self.assertIsNone(get_digital_feed_passport("SFA-NONEXISTENT-999"))


if __name__ == "__main__":
    unittest.main()
